services:
  api:
    image: taskflow:latest
    build:
      context: .
      args:
        APP_NAME: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro
    depends_on:
      - postgres-db
      - redis-db

  postgres-db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: taskflow

  redis-db:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
